spring:
  application:
    name: smartSafeReturn
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  api-docs:
    path: /api-docs        # OpenAPI 스펙 JSON 엔드포인트 경로
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 웹 인터페이스 경로
    default-models-expand-depth: -1  # 모델 섹션 기본 확장 깊이 (-1은 완전히 숨김)
    tags-sorter: alpha     # 태그 알파벳 순 정렬
    operations-sorter: alpha  # 작업 알파벳 순 정렬
  packages-to-scan: com.dodo  # API 스캔 대상 패키지

# cool sms 잔액 조회를 위한 커스텀
cool-sms:
  cost-per-sms: 20  # SMS 1건당 예상 비용 (기본값 20원)
  minimum-balance: 1000  # 최소 필요 잔액 (기본값 1000원)